@Library("test-codacy@main") _

pipeline {
  agent any
  stages {
    stage('checkout/clean') {
      steps {
        getCheckout('main')
      }
    }
    stage('stage1') {
      steps {
        echo "This is the $BUILD_NUMBER of demo $DEMO"
        script{
            String data = testLibrary.call()
            println data
             int maxDisplayMessages = 5
             String directory = 'C:/office'
             println getTestResultSummary.call(maxDisplayMessages, directory, "${env.BUILD_URL}testReport")
        }
        
        echo testLibrary()
        
      }
    }

  }
  environment {
    DEMO = '1.3'
  }
}
